language: java
jdk: oraclejdk13
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: script
  script: mvn deploy -P aws -Drun.jpa.tests=false
  on:
    branch: features/impl-aws-sign-up-ws
env:
  global:
  - secure: 63aIDyQ0tAa/wCzaYj6jXgkwFhGeUP3W0Epvi1ZX=
  - secure: AKIAIVVM4DA22CGZPFAQ=