matrix:
  include:
    - language: java
      jdk: oraclejdk11
      cache:
        directories:
          - "$HOME/.m2"
      deploy:
        provider: script
        script: mvn clean deploy -P aws
        on:
          branch: develop
      env:
        - secure: mx0M+EDJHI9AiPWNauWHxme1kRk1/oIMH2Z3dqO5pBYuKDHMJb8zSb40HzKbAUbhB6GaN2Mi/uBCx8NfO16/6x3YcMqn2XzkIXSqka9JAJoQmB0mqlFPV1y6eJ2nZEAd8lt7P1Z+2y4A+i5GurFkWtITdUjuQJoujvDc3mVrN8t5CNeOTly//DeQz8yvuka9gFQg3QrgukNi8iysEvOz2nEWI5+LS29XuO2znH6tPXQLStVhH48k0XrxyIT7U4ylDl30gPJxHSGxCI221ipSAHGFPRSiZQzYXwMftDseztA0XyvGocRzBS4yIHEmUvecscEUlZR/qztyf2GMBO1jZNub4misosawA7QWLPKsBb3J3hoPH86L4yt1a86TrW/40gmAKMU8kl/bpjHcsOzzSz4Il9Ebqx/uVayH5PNzOy6imSxMm6bQBDmyt/wVvuKkaE5NikiNjbXniHZNT8wqeFyJH53GxyqD72kIMQQXefuF8vQqpwIenYUdfVkx82acR+CIMFsqALY/tecE5Yz53vEN5Loe97+Cg8o1AB9XpB4AS+/8c6AkwlfOqMRYnvmwUrNfEP4HZoHwI7OG4hrp1HkiWTu6qFmnud1+4AJjyvl0bdvfmgdd1jYyFLEgBySovJDDAWYaXmkTraFDSMhy5jhMlMbNPOTpH4t0Os5mhW8=
        - secure: HRGKN9Z/+hlu7D1hJlNb9bnJSCaoSmKCx8Nydc5OlEbn8G8O+0sl7wKXlSFJYLMbzpgZcm56mlnS4mppKjsl1aaOZ2ILRdkgYFLJsUjH92vT/iykJ2tIJ9QjVNQsIv8PuOJy4AJKP9QW/c7a/+svFsx5VCycElmvL73zkEcYbmPflnn1M3i7gq5APYq8U9FI6K1/T0XPL+AfGsdKgiVbk8aj5pH4voMDF1hGAFByVxqWlZGLFhiEkd6OMgQ5WAzswANrs/ygzhTrN6cssATlXBq3zd0l/PJzkvW9SJ/L1R4WNOj7iONFGoYA0tDM2Z8rUqi8o0CLOCPGSrewNvfUNiwQTXcwDoA8ODVga6EWz2kFdaKSKhK/nVppeaRXAjxGQFo4ko8u3R552NF0H5p1MLTImF6wfBH5H09EM28CNfFQnIzWeNrjZH5EeqWwYIXM40zhVeSY+CGI4Ea1SUIQPzOfNquv9II0PjeNcNeanNb2q57L0igwc7evPlOhZf1JIWwbMC+wQrnvez7HCnF6kZSieFaDFWsmoqksxlwyfZZq3XFOwkB8bSwS1DxfyRJqWVoe7qnoC9SScmlm1PhHgJ4QzP4DDa8WEmku5c9ml9rJUA2uyq0ZcF7bt5kfItQAm8DrITX2E/Q6gUlGLDLysMLYkGxeLU3TPEwRXhB3MS4=
        - secure: NXY36JVtkF0FnnyoUsxbC23wUDCjdyg5Tsal2HWTAC3/E6P4mxiAzVVnVx/TI3YDrEirEEcqXdgEpZOvS7dWhWPbKS1Xm+NMLalOqaVukqPHl2R6iihsXx7wfpAsUjcH4bIWyILzjNdPtemUxDOunNcFu5Q6JXKG0b1oBdywKtRUc4XtJuaTuxOE3OSvgpUiFLDU1eui40i3K8FEINSEOUfmuk6Do5pmCmCke8UPm87e+55IdFvbJvNdT/lazLf/5K/CFLLjRn7ImSAATkjaR/cqQLUyjobg1fQM1zsM0gsVLH1nv6Fc1t6y9ORqbMN2wiroc210W4ElZ/PCRp3FmvnUCvPzSE/gzllrPD8VZrC2jH3akDkMgxFhFAMVao2FOTNGjoNsEjKrmENem9p+nzCqzFdfZA2t+FfAYdcAJmLM3VeOFpXqL3wquw/bfKWByaqjWpbpzNkqor6kCW7SPscSa7A3OGB/rwh42/5GDLHO+QJwXK7A9Bz8toyNHe4dE7j1JKAsr7+7gB3Ptzowoti5X8fWrGegVE6F6iI2gzRQJTlG7C+Oh0u5z/krVK95YiqswuxEPteuynmIuYKdQg3EyTUKTjWG2A+xvwO3ihY/h+RhAVE8ZF4zq+/HTXIvl4grReUK/rTzCAAPKB+lOVdDWnGG2Sa86uG4/J+xaRM=
        - secure: MO8ELN9hyB/w8zt3ek3+aihcYq5Rj+82qCb8i/rcbVhVdOavkN83S3k2Z1i7AV16xyLmcCc5EUJBdBabPX1F7R0oddQFlteKY6qnep3+nGjoZi2jipShKONvFBgl7qLRbtdlVXnNk3Nume0McO0dSUVAwNnIkZKbp1vvIU1I5yxY1zSePFzESs0aGeztNRhWMZdn4mKesOW2+aKsuJGxxU6lWuCj7FHCNeBbJPhKzpdiI+mcrqgRkyE0eafS6AHZhO1EVE4gj+04A6W2aOne/ASEGAhoOls4Mt8jU1QctTj3EjGg0TSQJ75KxUugiNTAJfiToAl/H9J4Jfn6Ig+tkL4vW0iz4bOaKLBcSCfhQ0oY5TSnBjCfQxx3eSijN2BvBNymULpdE5i015jfQ6TdYHyR+M3FpGfvLiJ6GCgXnthtzH6cAQMugu2ezTfcACDN2lzt99luAY501FapbUic8RGLcFqpirfWiuHEvyJ2jj9O4qVZgXxrDQHBvxvbTELSdvjfGx8r7eE8rioF8gpPhnck/G+9iRz4c8hb67TTKThu9IPx53defxzMUPzIO2oEj6JDNokoPdyE3ErtuMKR6cgXw5alEhDd8QiAni3e8qRMlDhbXFC/dSemRVz2/rGSrvRDjqvPSV8FnjqIuS2mq0bUxcv7VMcQfUIghXsOdzM=
        - secure: HR01oSZJ+gAoHprnVIiyopCIPppi211f1OM2e8KwaQcu4xVk1pfy0Awm8c5Cvt0XwT79XjMbt+DDR0JyxJv93rb475D8bht4bkxVR6psgC7pow2cwb6crEN9fiw21iKC01jg878++FAIpDTUu0PSm4LPgWA2GQbSYzJfOiA6eX3Rp54VIWf2gZhpDT31sp+t8m8yhhzQBFguhOXNf9XkrsNQgMpH27wXNIjBTgq0mu4EIPaqYpiMbthyAkise6eQSm8JCIaH4pSQuGkDb4Sb03FnuVY5e93x7Y1ezY3Ye4tfo06XwRprSZ2E3mTvstv88l6x9c4DtR2UTrOrEqSjXzRELZZM6MiDK3U5zudwKhdgVlzE2SLlrt4clo+M8VpC7spwX3Mh5Q9F6nyx21aiz1jbZQz3xfii4+3kXMrJ8oOM1nqrOUzfolILSx6Sz0Civ6RC3toEBbh9T9CECL28TqGlafDNlIL84V31zlvUuBraH+hPirVG3UnSSJDDo83xhkyHi+5cQ6Pa0l1cqjrl3tnYtrgKNYG27UGEjl8b+ytI3qnX4wLZKmOP1Sepv+vB6PY9e9NrY8naWEeSfCqXaIp9y0DrMeksQKqbyn/0s42b/qBaKJpFM9WrAUdxVITN0osxvQFNtSDalkyJfUdC7ffdmMtc/nwmaKKVZlqednQ=
    - language: node_js
      node_js:
        - “10”
      dist: trusty
      addons:
        chrome: stable
      cache:
        directories:
          - "chucks-pick3-mobile/node_modules"
      before_install:
        - cd chucks-pick3-mobile
        - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> .npmrc
        - npm config set //registry.npmjs.com/:_authToken=$NPM_TOKEN
        - npm install -g @ionic/cli
      install:
        - npm install
        - npm install --only=dev
      script:
        - npm run test:ci
      env:
        - secure: bBmquLkb59FYWKo9Ho3dMVvt28NXAdBNy2deg/oi8bfc74FW7VNsFFnFGS8hJMDEBNH9AJuCH9MdYdfenT55nv6nwAWB6PzUveRRF0YtYQQ42VfF4HcgyBbIaFLG82KU5mhbWhVgrvQdnMxf7RT9KaJHuFEfSh2CxeElgfk9pynjeXGiIPpxc5zzeHDluBywZpYmGXWGdlZVhRTy4mzsNiBaypBakt9McervDWd7zjfn4v+MOLO0mBFrzXRb8664XPDJhNTofd/nsBUmQV0DDI54yv5mnzyuHvD409CJprAjlgyLFXPFkRtxuV/dNX0Uz2xHhj5yVivmQZ2gf1smFu6uVzxxnr6mx7L6OBsWxHQPkuTj8olSAFhCRL11wFCB6u9ypSV4sUTmSNJpND9xKSL5s4uaocJgGK2gyPbpImPJ2mdOpbui0tMeHH7+tjiwYyY2gOvSHHocWsZgfFT3vjoUrrj0RPtJlap2G7vF+yTSs8jNCX4b7VoeNlJL1r2AxtO94utE/e72B4C/2zNiv2CpW+8eznHAPlcEUecslWLLDJslY7L0wedeV78cvu5tek4S/FoGL6bW69e1X99Iv7h5EjHzQdCL33omETuK1GR3+PPlLw6fiFpr2l1Qr7zZ7DInpIO09jLx9qb0Ym/TMKZDbTltGbW9yW9jAv0ZxKI=
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - amanjotabroljava@gmail.com
    on_success: always
    on_failure: always
