spring.profiles.active: dev
config:
  numPlaysToPredict: 10
errors:
  winNumber:
    past: "winDate must be in the past."
  futureDrawDate:
    future: "futureDrawDate must be in the future."
