AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring API - software.bytepushers.pick3::aws-api-gateway-sample
Outputs:
  AwsApiGatewaySampleApi:
    Description: Root URL for application
    Export:
      Name: AwsApiGatewaySampleApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
Resources:
  AwsApiGatewaySampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://${bytepushers.deploy.s3BucketName}/${bytepushers.deploy.s3ObjectName}
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: software.bytepushers.pick3.StreamLambdaHandler::handleRequest
      MemorySize: 256
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 15