language: node_js
node_js:
   - "v8.5.0"
branches:
  only:
  - master
  - develop
  - features/plws-8-setup-continuous-deployment-to-aws

notifications:
  email:
    recipients:
      - kenneth_flow@hotmail.com
    on_success: change # default: change
    on_failure: always # default: always

jobs:
  include:
    - stage: test
      script: npm test
stages:
  - test